packages:
  - 'clients/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - eslint-plugin-react-refresh@0.5.7
  - '@tanstack/query-core@5.103.1'
  - '@tanstack/react-query@5.103.1'
  - jsdom@30.1.0
